### PR TITLE
Added video functionality and play pause button

### PR DESCRIPTION
**Pull request by Devika-Rudagi**
Added Video and play-pause button

### CODE REVIEW

**Comment by Devika-Rudagi** [comment]
Hi, I had a solution to the PR.

**Review by bijiyiqi2017 — CHANGES_REQUESTED** [review]
Hello,

Thank you so much for your contribution to the project! We really appreciate the time and effort you've put into this.

I had a chance to review your recent pull request, and while it's definitely moving in the right direction, there are just a few small adjustments that would help align it more closely with our codebase and standards:

Video Controls: It looks like the custom video controls are using pointer-events: none, which is preventing user interaction with the buttons. Could you please update this to allow for interaction (pointer-events: auto)? This way, users will be able to engage with the play/pause functionality more easily.

Responsiveness: The controls are currently positioned using transform: translateX(-50%). While this centers them horizontally, it would be great if you could ensure they also adjust vertically when the video is resized. Adding a bottom: 10px or using CSS Flexbox could help improve this positioning.

Z-index: To make sure the controls are visible above the video content, adding a z-index property might be necessary. Could you try setting a z-index: 10 to ensure the controls don't get overlapped?

I’m confident that these tweaks will make your contribution even stronger. Once you’ve made these changes, feel free to push the updates, and we’ll take another look!

Thank you again for your hard work—it's clear that you've put a lot of thought into this, and we're excited to see the final version! 😊

Best regards,
Bill
GitHub Repo Maintainer

**Comment by Devika-Rudagi** [comment]
Hi @bijiyiqi2017 
Thanks for the feedback. I have made the necessary changes as per requests. Let me know is this what you were looking for?
https://github.com/bijiyiqi2017/dragon24/pull/6/commits/e1ed87a3cf256029505c8a00dbb435692c5ea317

**Review by bijiyiqi2017 — APPROVED** [review]
Thanks for your contributions

**Comment by bijiyiqi2017** [comment]
Thank you for your valuable contributions! Your efforts enhance this project significantly. If you find it helpful, please consider starring this repository; it really supports our community and helps others discover it. We encourage you to keep contributing here and to other repositories in the future. Best of luck with the Hacktober Fest 2024 Challenge! Your participation is greatly appreciated!

**Comment by bijiyiqi2017** [comment]
@all-contributors please add Devika-Rudagi for code

**Pull request merged**
