### PR TITLE
Add Translated README Files

### PR DESCRIPTION
**Pull request by abbasabro**
This pull request introduces two new README files for the "Dragon Fruit Delight" project, aimed at improving accessibility for non-English speakers and promoting inclusivity within the developer community.

Changes Made:
README.zh-cn.md:

1.Fully translated version of the README file into Mandarin Chinese (Simplified Characters).
2.All sections have been translated while preserving the original formatting, links, and technical terms.
README.bilingual.md:

A bilingual version containing English and Mandarin translations side-by-side.
1.This format allows readers to easily compare the original text with its translation, enhancing understanding for bilingual users.

I welcome any feedback or suggestions to further improve the translations.
Looking forward to merging these files to enhance the project's documentation!
Thank you for considering this pull request!

### CODE REVIEW

**Review by abbasabro — COMMENTED** [review]
I have reviewed my pull request

**Review by abbasabro — COMMENTED** [review]
Can you approve the pull request

**Review by bijiyiqi2017 — APPROVED** [review]
Thank you for your valuable contributions! Your efforts enhance this project significantly. If you find it helpful, please consider starring this repository; it really supports our community and helps others discover it. We encourage you to keep contributing here and to other repositories in the future. Best of luck with the Hacktober Fest 2024 Challenge! Your participation is greatly appreciated!

**Comment by abbasabro** [comment]
You're welcome! I'm glad to contribute. I have starred the repository and
look forward to contributing more in the future. Thanks for the
encouragement!!

**Comment by bijiyiqi2017** [comment]
@all-contributors please add abbasabro for doc

**Pull request merged**
